### ISSUE TITLE
master and develop branch do not compile

### ISSUE THREAD

**Issue by valkenburg** [coccoinomane/song#8]
Hi friends,

it looks like a number of files is missing in the git repository:
`make: *** No rule to make target `utility.o', needed by `song'.  Stop.`
`make: *** No rule to make target `bessel.o', needed by `song'.  Stop.`

and many more of those. When will those files be added to the public code?

For info: I downloaded the zip file from github, I put a plain version of CLASS in class.git, and hit `make`.

**Comment by coccoinomane** [comment]
Ciao Wessel!

It's great to meet you again in a Github repository after such a long time :-)

In order to install SONG you should clone the repository using the `recursive` flag, as documented in the README:

`git clone --recursive https://github.com/coccoinomane/song.git song.git`

The `recursive` flag will make sure that the proper version of CLASS is downloaded => [my fork of CLASS](https://github.com/coccoinomane/class_public/tree/2643d443635e97959e6353904773e06e3ecbd793), which is vanilla CLASS modified in order to be compatible with SONG.

If you want to implement some custom modifications to CLASS, you can just fork my CLASS fork and merge your modifications there.

Please let me know if this works :-)
Cheers,
Guido

**Comment by valkenburg** [comment]
Hi Guido,

Oops, I should have read the manual...... My bad. It compiles just fine now, straight out of the box. Thanks for the quick answer!

Cheers,
Wessel

**Comment by coccoinomane** [comment]
No worries Wessel :-) Feel free to ask if you need help with getting SONG running! 

Ciao,
Guido
